project:
  type: website

website:
  title: "Imputation and PGS Tutorial"
  page-navigation: true
  bread-crumbs: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Getting Started"
        href: getting-started.qmd
      - text: "Data"
        href: data.qmd
        icon: download
      - text: "Tutorials"
        icon: book
        menu:
          - href: imputation.qmd
            icon: gear
          - href: pgs-calculation.qmd
            icon: gear            
          - href: local-imputation.qmd
            icon: gear                       
          - href: gwas-with-nf-gwas.qmd
            icon: bar-chart
          - href: gwas-with-plink2.qmd
            icon: bar-chart
          - href: pgs.qmd
            icon: activity    
    right:
      - text: "About"
        href: about.qmd
format:
  html:
    theme: [cosmo, theme.scss]
    toc: true

bibliography: references.bib