project:
  type: website

website:
  title: "Imputation and PGS Tutorial"
  page-navigation: true
  bread-crumbs: true  
  navbar:
    background: light
    search: true  
    left:
      - getting-started.qmd
      - data.qmd
      - text: "Tutorials"
        menu:
          - imputation.qmd
          - gwas-with-nf-gwas.qmd
          - gwas-with-plink2.qmd
          - pgs.qmd

format:
  html:
    toc: true

bibliography: references.bib



