name: imputation-and-pgs-tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - quarto=1.7.30
  - r-rmarkdown=2.29
  - plink2=2.0.0a.6.9
  - r-qqman=0.1.9
  - r-ggplot2=3.5.2
  - r-dplyr
  - r-readr
