# Getting Started

## Requirements

Before starting, install the following tools and packages. Keep in mind that not all of the following tools and datasets are required for every analysis. The exact setup depends on whether you're performing imputation, GWAS, or PGS.

1. **Account** on [Michigan Imputation Server](https://imputationserver.sph.umich.edu/) -  required for genotype imputation.

2. **Data** - Download the genotype and phenotype datasets provided [here](/data.html). These files are required for the imputation, GWAS or Polygenic Score (PGS) analyses.

3. **PLINK2** – used for running a GWAS analysis. Download plink2 from [here](https://www.cog-genomics.org/plink/2.0/)

   Test installation:

   ```bash
   plink2 --version
   ```

4. **R** – statistical computing environment used for Polygenic Score (PGS) analysis
   [Install R](https://cran.r-project.org/)

5. **RStudio** – IDE for R 
   [Install RStudio](https://posit.co/download/rstudio/)

6. **R Packages** – for data visualization of PGS scores
   In R or RStudio, run:

   ```R
   install.packages(c("ggplot2", "qqman"))
   ```

